INCLUDE_CRITERIA = [
    "Web development, web apps, dashboards, websites, or frontend/full-stack product engineering.",
    "React, Next.js, TypeScript, JavaScript, or non-framework-specific web development.",
    "Mobile app work using React Native or Expo.",
    "Generative AI, LLM, agent, chatbot, or AI-powered product work where reasoning/product integration matters.",
    "Backend work only when the backend stack includes Python or JavaScript/TypeScript/Node.js.",
]

EXCLUDE_CRITERIA = [
    "Mobile roles that are primarily Swift, iOS-native, Kotlin, Android-native, Java Android, Flutter, or Dart.",
    "Frontend roles that are specifically Vue, Svelte, jQuery, Angular-only, or another non-React framework.",
    "MLOps, ML platform, data infrastructure, model training, computer vision research, or data science roles.",
    "Robotics, embedded systems, hardware operations, factory automation, or physical systems roles.",
    "DevOps/SRE/infrastructure-only roles with no web, mobile, or GenAI product scope.",
    "Backend or full-stack roles where the backend stack is Go/Golang, Elixir/Phoenix, Ruby/Rails, Kotlin/JVM/Spring, C#, C++, Rust, Java, or other unsupported backend stacks and there is no Python, Node.js, or JavaScript/TypeScript backend.",
    "Reject unsupported backend stacks even if the job says language-agnostic, stack-agnostic, or that strong engineers can learn the stack. The applicant does not want to learn new backend technologies.",
    "Full-stack roles where the frontend stack is strictly Vue, Svelte, Angular, jQuery, or another non-React frontend.",
    "Strict onsite/in-office roles. Remote, hybrid, WFH flexibility, or onsite-or-remote roles are acceptable.",
    "US-only residency roles, US-only remote roles, or roles with no visa sponsorship when the applicant must live in the United States.",
    "Internships or student-only roles.",
    "Cofounder/co-founder roles, equity-only roles, unpaid/deferred-pay roles, pay-when-profitable roles, commission-only roles, missing cash compensation, or roles with very low cash compensation.",
    "Solutions engineer, sales engineer, product marketing, and design-only roles.",
    "Stale postings older than about one month or listings too thin to judge.",
]

KEYWORD_INCLUDE = {
    "web": [
        "web developer",
        "web engineer",
        "frontend",
        "front-end",
        "fullstack",
        "full-stack",
        "full stack",
        "back end",
        "react",
        "next.js",
        "nextjs",
        "typescript",
        "javascript",
        "website",
        "dashboard",
    ],
    "mobile": ["react native", "expo", "mobile app"],
    "ai": [
        "generative ai",
        "gen ai",
        "ai engineer",
        "artificial intelligence",
        "llm",
        "large language model",
        "ai agent",
        "chatbot",
        "ai-powered",
        "ai powered",
        "openai",
    ],
    "backend": [
        "python",
        "fastapi",
        "django",
        "flask",
        "node.js",
        "nodejs",
        "typescript backend",
        "javascript backend",
        "backend",
    ],
}

KEYWORD_EXCLUDE = [
    "swift",
    "kotlin",
    "android",
    "android engineer",
    "android developer",
    "ios",
    "ios engineer",
    "ios developer",
    "compose multiplatform",
    "flutter",
    "dart",
    "vue",
    "svelte",
    "jquery",
    "angular",
    "mlops",
    "llmops",
    "machine learning platform",
    "ai platform",
    "data engineer",
    "data platform",
    "model serving",
    "data scientist",
    "data science",
    "causal inference",
    "predictive modeling",
    "alternative-data",
    "alternative data",
    "robotics",
    "robotic",
    "embedded",
    "ai trainer",
    "freelance ai trainer",
    "computer vision",
    "model training",
    "kubernetes",
    "devops engineer",
    "sre",
    "infrastructure engineer",
    "cloud ai infrastructure",
    "bess engineer",
    "r engineer",
    "engineering specialist",
    "problem solver",
    "computational engineering",
]


def criteria_prompt() -> str:
    include = "\n".join(f"- {item}" for item in INCLUDE_CRITERIA)
    exclude = "\n".join(f"- {item}" for item in EXCLUDE_CRITERIA)
    return f"Include criteria:\n{include}\n\nExclude criteria:\n{exclude}"
